apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-nodeapp-job
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: canary-svc
      stableService: stable-svc
      trafficRouting:
        istio:
          virtualService:
            name: rollout-vsvc-nodeapp-job
            routes:
              - primary
      steps:
        - setWeight: 20
        - pause: { duration: 60 }
        - analysis:
            templates:
              - templateName: job-nodeapp
            args:
              - name: host
                value: canary-svc
              - name: port
                value: "80"
              - name: respCode
                value: "200"
        - setWeight: 40
        - pause: { duration: 60 }
        - analysis:
            templates:
              - templateName: job-nodeapp
            args:
              - name: host
                value: canary-svc
              - name: port
                value: "80"
              - name: respCode
                value: "200"
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nodeapp-job
  template:
    metadata:
      labels:
        app: nodeapp-job
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
        prometheus.io/serviceversion: "v01"
    spec:
      containers:
        - image: albertogarces/nodeapp-01:v01
          name: nodeapp-01
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /liveOK
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyOK
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3

---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: job-nodeapp
spec:
  args:
    - name: host
    - name: port
    - name: respCode
  metrics:
    - name: job-nodeapp
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              metadata:
                annotations:
                  sidecar.istio.io/inject: “false”
              spec:
                containers:
                  - name: jobtest
                    image: albertogarces/nodeapp-01-test:v01
                    imagePullPolicy: Always
                    command:
                      [
                        "/bin/sh",
                        "index.sh",
                        "{{args.host}}",
                        "{{args.port}}",
                        "{{args.respCode}}",
                      ]
                restartPolicy: Never

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-rollout-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - argorollouts-rollouttestjob-euwest1.*

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollout-vsvc-nodeapp-job
spec:
  gateways:
    - istio-rollout-gateway
  hosts:
    - argorollouts-rollouttestjob-euwest1.*
  http:
    - name: primary
      route:
        - destination:
            host: stable-svc
          weight: 100
        - destination:
            host: canary-svc
          weight: 0

---
apiVersion: v1
kind: Service
metadata:
  name: stable-svc
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: nodeapp-job

---
apiVersion: v1
kind: Service
metadata:
  name: canary-svc
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: nodeapp-job
