apiVersion: v1
kind: Namespace
metadata:
  name: rollouttest-prometheus
  labels:
    istio-injection: enabled

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-nodeapp-prometheus
  namespace: rollouttest-prometheus
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: canary-svc
      stableService: stable-svc
      trafficRouting:
        istio:
          virtualService:
            name: rollout-vsvc-nodeapp-prometheus
            routes:
              - primary
      steps:
      - setWeight: 20
      - analysis:
          templates:
          - templateName: analysistemplate-nodeapp-prometheus

  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nodeapp-prometheus
  template:
    metadata:
      labels:
        app: nodeapp-prometheus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
        prometheus.io/serviceversion: "v01"
    spec:
      containers:
        - image: albertogarces/nodeapp-01:v01
          name: nodeapp-01
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /liveOK
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyOK
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3

---

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: analysistemplate-nodeapp-prometheus
  namespace: rollouttest-prometheus
spec:
  metrics:
  - name: analysistemplate-nodeapp-prometheus-metric
    interval: 10s
#     successCondition: result[0] > 0.0
#     failureCondition: result[0] < 0.0
    failureLimit: 5
    count: 5
    provider:
      prometheus:
        address: http://prometheus-server.prometheus:80
        query: |
          (sum(test_counter{code="200",serviceversion="v02"}) or vector (0)) - (sum(test_counter{code="500",serviceversion="v02"}) or vector (0))

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-rollout-gateway
  namespace: rollouttest-prometheus
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollout-vsvc-nodeapp-prometheus
  namespace: rollouttest-prometheus
spec:
  gateways:
    - istio-rollout-gateway
  hosts:
    - "*"
  http:
    - name: primary
      route:
        - destination:
            host: stable-svc
          weight: 100
        - destination:
            host: canary-svc
          weight: 0

---
apiVersion: v1
kind: Service
metadata:
  name: stable-svc
  namespace: rollouttest-prometheus
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: nodeapp-prometheus

---
apiVersion: v1
kind: Service
metadata:
  name: canary-svc
  namespace: rollouttest-prometheus
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: nodeapp-prometheus
